import { action } from '../../common';
export const types = {
    FETCH_COMPLAINT_DETAILS: 'FETCH_COMPLAINT_DETAILS',
    FETCH_COMPLAINT_DETAILS_REQUEST: 'FETCH_COMPLAINT_DETAILS_REQUEST',
    FETCH_COMPLAINT_DETAILS_SUCCESS: 'FETCH_COMPLAINT_DETAILS_SUCCESS',
    FETCH_COMPLAINT_DETAILS_FAILURE: 'FETCH_COMPLAINT_DETAILS_FAILURE',

    ASSIGN_SERVICE_WORKER: 'Complaints/ASSIGN_SERVICE_WORKER',
    ASSIGN_SERVICE_WORKER_REQUEST: 'Complaints/ASSIGN_SERVICE_WORKER_REQUEST',
    ASSIGN_SERVICE_WORKER_SUCCESS: 'Complaints/ASSIGN_SERVICE_WORKER_SUCCESS',
    ASSIGN_SERVICE_WORKER_FAILURE: 'Complaints/ASSIGN_SERVICE_WORKER_FAILURE'
};

export const fetchComplaintDetails = (data) => action(types.FETCH_COMPLAINT_DETAILS, { data });

export const assignComplaintsServiceWorker = (data) => action(types.ASSIGN_SERVICE_WORKER, { data });
