import { action } from '../../common';
export const types = {
    FETCH_LSGI_DETAILS: 'BasicConfig/FETCH_LSGI_DETAILS',
    FETCH_LSGI_DETAILS_REQUEST: 'BasicConfig/FETCH_LSGI_DETAILS_REQUEST',
    FETCH_LSGI_DETAILS_SUCCESS: 'BasicConfig/FETCH_LSGI_DETAILS_SUCCESS',
    FETCH_LSGI_DETAILS_FAILURE: 'BasicConfig/FETCH_LSGI_DETAILS_FAILURE',

    FETCH_LSGI_DETAILS_BY_ID: 'BasicConfig/FETCH_LSGI_DETAILS_BY_ID',
    FETCH_LSGI_DETAILS_BY_ID_REQUEST: 'BasicConfig/FETCH_LSGI_DETAILS_BY_ID_REQUEST',
    FETCH_LSGI_DETAILS_BY_ID_SUCCESS: 'BasicConfig/FETCH_LSGI_DETAILS_BY_ID_SUCCESS',
    FETCH_LSGI_DETAILS_BY_ID_FAILURE: 'BasicConfig/FETCH_LSGI_DETAILS_BY_ID_FAILURE',

    SAVE_LSGI_DETAILS: 'BasicConfig/SAVE_LSGI_DETAILS',
    SAVE_LSGI_DETAILS_REQUEST: 'BasicConfig/SAVE_LSGI_DETAILS_REQUEST',
    SAVE_LSGI_DETAILS_SUCCESS: 'BasicConfig/SAVE_LSGI_DETAILS_SUCCESS',
    SAVE_LSGI_DETAILS_FAILURE: 'BasicConfig/SAVE_LSGI_DETAILS_FAILURE',

    UPDATE_LSGI_DETAILS: 'BasicConfig/UPDATE_LSGI_DETAILS',
    UPDATE_LSGI_DETAILS_REQUEST: 'BasicConfig/UPDATE_LSGI_DETAILS_REQUEST',
    UPDATE_LSGI_DETAILS_SUCCESS: 'BasicConfig/UPDATE_LSGI_DETAILS_SUCCESS',
    UPDATE_LSGI_DETAILS_FAILURE: 'BasicConfig/UPDATE_LSGI_DETAILS_FAILURE',

    DELETE_LSGI_DETAILS: 'BasicConfig/DELETE_LSGI_DETAILS',
    DELETE_LSGI_DETAILS_REQUEST: 'BasicConfig/DELETE_LSGI_DETAILS_REQUEST',
    DELETE_LSGI_DETAILS_SUCCESS: 'BasicConfig/DELETE_LSGI_DETAILS_SUCCESS',
    DELETE_LSGI_DETAILS_FAILURE: 'BasicConfig/DELETE_LSGI_DETAILS_FAILURE',

    LIST_DISTRICT: 'BasicConfig/LIST_DISTRICT',
    LIST_DISTRICT_REQUEST: 'BasicConfig/LIST_DISTRICT_REQUEST',
    LIST_DISTRICT_SUCCESS: 'BasicConfig/LIST_DISTRICT_SUCCESS',
    LIST_DISTRICT_FAILURE: 'BasicConfig/LIST_DISTRICT_FAILURE',

    CLEAR_LSGI_DETAILS_REDUCER: 'BasicConfig/CLEAR_LSGI_DETAILS_REDUCER',

    LOAD_LSGI_TYPES: 'BasicConfig/LOAD_LSGI_TYPES',
    LOAD_LSGI_TYPES_REQUEST: 'BasicConfig/LOAD_LSGI_TYPES_REQUEST',
    LOAD_LSGI_TYPES_SUCCESS: 'BasicConfig/LOAD_LSGI_TYPES_SUCCESS',
    LOAD_LSGI_TYPES_FAILURE: 'BasicConfig/LOAD_LSGI_TYPES_FAILURE',

    LOAD_BLOCK_PANCHAYATH: 'BasicConfig/LOAD_BLOCK_PANCHAYATH',
    LOAD_BLOCK_PANCHAYATH_REQUEST: 'BasicConfig/LOAD_BLOCK_PANCHAYATH_REQUEST',
    LOAD_BLOCK_PANCHAYATH_SUCCESS: 'BasicConfig/LOAD_BLOCK_PANCHAYATH_SUCCESS',
    LOAD_BLOCK_PANCHAYATH_FAILURE: 'BasicConfig/LOAD_BLOCK_PANCHAYATH_FAILURE'


};
export const fetchLSGIDetails = (data) => action(types.FETCH_LSGI_DETAILS, { data });
export const saveLSGIsData = (data) => action(types.SAVE_LSGI_DETAILS, { data });
export const updateLSGIsData = (id, data) => action(types.UPDATE_LSGI_DETAILS, { id, data });
export const deleteLSGIsData = (data, size, page) => action(types.DELETE_LSGI_DETAILS, { data, size, page });
export const fetchLSGIsById = (data) => action(types.FETCH_LSGI_DETAILS_BY_ID, { data });
export const clearReducer = () => action(types.CLEAR_LSGI_DETAILS_REDUCER);
export const fetchDistrictList = (data) => action(types.LIST_DISTRICT, { data });
export const fetchLSGItype = () => action(types.LOAD_LSGI_TYPES);
export const fetchBlockPanchayath = (data) => action(types.LOAD_BLOCK_PANCHAYATH, { data });
