
import { action } from '../../common';

export const types = {
    LOAD_DISTRICT: 'dashBoard/LOAD_DISTRICT',
    LOAD_DISTRICT_REQUEST: 'dashBoard/LOAD_DISTRICT_REQUEST',
    LOAD_DISTRICT_SUCCESS: 'dashBoard/LOAD_DISTRICT_SUCCESS',
    LOAD_DISTRICT_FAILURE: 'dashBoard/LOAD_DISTRICT_FAILURE',

    LOAD_LSGI: 'dashBoard/LOAD_LSGI',
    LOAD_LSGI_REQUEST: 'dashBoard/LOAD_LSGI_REQUEST',
    LOAD_LSGI_SUCCESS: 'dashBoard/LOAD_LSGI_SUCCESS',
    LOAD_LSGI_FAILURE: 'dashBoard/LOAD_LSGI_FAILURE',

    LOAD_LSGI_TYPE: 'dashBoard/LOAD_LSGI_TYPE',
    LOAD_LSGI_TYPE_REQUEST: 'dashBoard/LOAD_LSGI_TYPE_REQUEST',
    LOAD_LSGI_TYPE_SUCCESS: 'dashBoard/LOAD_LSGI_TYPE_SUCCESS',
    LOAD_LSGI_TYPE_FAILURE: 'dashBoard/LOAD_LSGI_TYPE_FAILURE',

    LOAD_TOTAL_CHILD_COUNT: 'dashBoard/LOAD_TOTAL_CHILD_COUNT',
    LOAD_TOTAL_CHILD_COUNT_REQUEST: 'dashBoard/LOAD_TOTAL_CHILD_COUNT_REQUEST',
    LOAD_TOTAL_CHILD_COUNT_SUCCESS: 'dashBoard/LOAD_TOTAL_CHILD_COUNT_SUCCESS',
    LOAD_TOTAL_CHILD_COUNT_FAILURE: 'dashBoard/LOAD_TOTAL_CHILD_COUNT_FAILURE',

    LOAD_TOTAL_PARENT_COUNT: 'dashBoard/LOAD_TOTAL_PARENT_COUNT',
    LOAD_TOTAL_PARENT_COUNT_REQUEST: 'dashBoard/LOAD_TOTAL_PARENT_COUNT_REQUEST',
    LOAD_TOTAL_PARENT_COUNT_SUCCESS: 'dashBoard/LOAD_TOTAL_PARENT_COUNT_SUCCESS',
    LOAD_TOTAL_PARENT_COUNT_FAILURE: 'dashBoard/LOAD_TOTAL_PARENT_COUNT_FAILURE',

    LOAD_TOTAL_TEACHERS_COUNT: 'dashBoard/LOAD_TOTAL_TEACHERS_COUNT',
    LOAD_TOTAL_TEACHERS_COUNT_REQUEST: 'dashBoard/LOAD_TOTAL_TEACHERS_COUNT_REQUEST',
    LOAD_TOTAL_TEACHERS_COUNT_SUCCESS: 'dashBoard/LOAD_TOTAL_TEACHERS_COUNT_SUCCESS',
    LOAD_TOTAL_TEACHERS_COUNT_FAILURE: 'dashBoard/LOAD_TOTAL_TEACHERS_COUNT_FAILURE',

    LOAD_TOTAL_GENERAL_PUBLIC_COUNT: 'dashBoard/LOAD_TOTAL_GENERAL_PUBLIC_COUNT',
    LOAD_TOTAL_GENERAL_PUBLIC_COUNT_REQUEST: 'dashBoard/LOAD_TOTAL_GENERAL_PUBLIC_COUNT_REQUEST',
    LOAD_TOTAL_GENERAL_PUBLIC_COUNT_SUCCESS: 'dashBoard/LOAD_TOTAL_GENERAL_PUBLIC_COUNT_SUCCESS',
    LOAD_TOTAL_GENERAL_PUBLIC_COUNT_FAILURE: 'dashBoard/LOAD_TOTAL_GENERAL_PUBLIC_COUNT_FAILURE',

    LOAD_TOTAL_OFFICIALS_COUNT: 'dashBoard/LOAD_TOTAL_OFFICIALS_COUNT',
    LOAD_TOTAL_OFFICIALS_COUNT_REQUEST: 'dashBoard/LOAD_TOTAL_OFFICIALS_COUNT_REQUEST',
    LOAD_TOTAL_OFFICIALS_COUNT_SUCCESS: 'dashBoard/LOAD_TOTAL_OFFICIALS_COUNT_SUCCESS',
    LOAD_TOTAL_OFFICIALS_COUNT_FAILURE: 'dashBoard/LOAD_TOTAL_OFFICIALS_COUNT_FAILURE',

    LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT: 'dashBoard/LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT',
    LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT_REQUEST: 'dashBoard/LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT_REQUEST',
    LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT_SUCCESS: 'dashBoard/LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT_SUCCESS',
    LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT_FAILURE: 'dashBoard/LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT_FAILURE'


};
export const loadDistrict = () => action(types.LOAD_DISTRICT);
export const loadLSGI = (lsgiId, districtId, blockPanchayathId) => action(types.LOAD_LSGI, { lsgiId, districtId, blockPanchayathId });
export const loadLSGIType = () => action(types.LOAD_LSGI_TYPE);

export const loadTotalChildCount = (data) => action(types.LOAD_TOTAL_CHILD_COUNT, { data });
export const loadTotalParentCount = (data) => action(types.LOAD_TOTAL_PARENT_COUNT, { data });
export const loadTotalTeacherCount = (data) => action(types.LOAD_TOTAL_TEACHERS_COUNT, { data });
export const loadGeneralPublicCount = (data) => action(types.LOAD_TOTAL_GENERAL_PUBLIC_COUNT, { data });
export const loadOfficialCount = (data) => action(types.LOAD_TOTAL_OFFICIALS_COUNT, { data });
export const loadComplaintReceivedCount = (data) => action(types.LOAD_TOTAL_COMPLAINT_RECEIVED_COUNT, { data });
