import { action } from '../../common';
import _ from '../../utils/LodashUtils';

export const types = {
    SAVE_USER_GROUP: 'UserGroups/SAVE_USER_GROUP',
    SAVE_USER_GROUP_REQUEST: 'UserGroups/SAVE_USER_GROUP_REQUEST',
    SAVE_USER_GROUP_SUCCESS: 'UserGroups/SAVE_USER_GROUP_SUCCESS',
    SAVE_USER_GROUP_FAILED: 'UserGroups/SAVE_USER_GROUP_FAILED',

    UPDATE_USER_GROUP: 'UserGroups/UPDATE_USER_GROUP',
    UPDATE_USER_GROUP_REQUEST: 'UserGroups/UPDATE_USER_GROUP_REQUEST',
    UPDATE_USER_GROUP_SUCCESS: 'UserGroups/UPDATE_USER_GROUP_SUCCESS',
    UPDATE_USER_GROUP_FAILED: 'UserGroups/UPDATE_USER_GROUP_FAILED',

    LIST_USER_GROUP: 'UserGroups/LIST_USER_GROUP',
    LIST_USER_GROUP_REQUEST: 'UserGroups/LIST_USER_GROUP_REQUEST',
    LIST_USER_GROUP_SUCCESS: 'UserGroups/LIST_USER_GROUP_SUCCESS',
    LIST_USER_GROUP_FAILED: 'UserGroups/LIST_USER_GROUP_FAILED',

    DELETE_USER_GROUP: 'UserGroups/DELETE_USER_GROUP',
    DELETE_USER_GROUP_REQUEST: 'UserGroups/DELETE_USER_GROUP_REQUEST',
    DELETE_USER_GROUP_SUCCESS: 'UserGroups/DELETE_USER_GROUP_SUCCESS',
    DELETE_USER_GROUP_FAILED: 'UserGroups/DELETE_USER_GROUP_FAILED',

    UPDATE_CURRENT_USER_GROUP: 'UserGroups/UPDATE_CURRENT_USER_GROUP',
    UPDATE_CURRENT_USER_GROUP_REQUEST: 'UserGroups/UPDATE_CURRENT_USER_GROUP_REQUEST',
    UPDATE_CURRENT_USER_GROUP_SUCCESS: 'UserGroups/UPDATE_CURRENT_USER_GROUP_SUCCESS',
    UPDATE_CURRENT_USER_GROUP_FAILED: 'UserGroups/UPDATE_CURRENT_USER_GROUP_FAILED',

    GET_USER_GROUP_BY_ID: 'UserGroups/GET_USER_GROUP_BY_ID',
    GET_USER_GROUP_BY_ID_REQUEST: 'UserGroups/GET_USER_GROUP_BY_ID_REQUEST',
    GET_USER_GROUP_BY_ID_SUCCESS: 'UserGroups/GET_USER_GROUP_BY_ID_SUCCESS',
    GET_USER_GROUP_BY_ID_FAILED: 'UserGroups/GET_USER_GROUP_BY_ID_FAILED',

    FETCH_USERS_BY_USER_GROUP: 'UserGroups/FETCH_USERS_BY_USER_GROUP',
    FETCH_USERS_BY_USER_GROUP_REQUEST: 'UserGroups/FETCH_USERS_BY_USER_GROUP_REQUEST',
    FETCH_USERS_BY_USER_GROUP_SUCCESS: 'UserGroups/FETCH_USERS_BY_USER_GROUP_SUCCESS',
    FETCH_USERS_BY_USER_GROUP_FAILURE: 'UserGroups/FETCH_USERS_BY_USER_GROUP_FAILURE',

    UPDATE_USERS_IN_USER_GROUP: 'UserGroups/UPDATE_USERS_IN_USER_GROUP',
    UPDATE_USERS_IN_USER_GROUP_REQUEST: 'UserGroups/UPDATE_USERS_IN_USER_GROUP_REQUEST',
    UPDATE_USERS_IN_USER_GROUP_SUCCESS: 'UserGroups/UPDATE_USERS_IN_USER_GROUP_SUCCESS',
    UPDATE_USERS_IN_USER_GROUP_FAILURE: 'UserGroups/UPDATE_USERS_IN_USER_GROUP_FAILURE',

    RESET_FORM: 'UserGroups/RESET_FORM',
    STORE_JSON_DATA_FOR_USER_GROUP: 'UserManagement/STORE_JSON_DATA_FOR_USER_GROUP',
    SET_USER_GROUP_TAB_INDEX: 'UserGroup/SET_USER_GROUP_TAB_INDEX',

    ASSIGN_USERS_UNDER_USER_GROUP: 'UserGroups/ASSIGN_USERS_UNDER_USER_GROUP',
    ASSIGN_USERS_UNDER_USER_GROUP_REQUEST: 'UserGroups/ASSIGN_USERS_UNDER_USER_GROUP_REQUEST',
    ASSIGN_USERS_UNDER_USER_GROUP_SUCCESS: 'UserGroups/ASSIGN_USERS_UNDER_USER_GROUP_SUCCESS',
    ASSIGN_USERS_UNDER_USER_GROUP_FAILURE: 'UserGroups/ASSIGN_USERS_UNDER_USER_GROUP_FAILURE',

    SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP: 'UserGroup/SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP',
    SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP_REQUEST: 'UserGroup/SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP_REQUEST',
    SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP_SUCCESS: 'UserGroup/SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP_SUCCESS',
    SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP_FAILURE: 'UserGroup/SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP_FAILURE'

};

export const listUserGroup = (data) => action(types.LIST_USER_GROUP, { data });

export const deleteUserGroup = (data, page, size, count) => action(types.DELETE_USER_GROUP, { data, page, size, count });

export const saveUserGroup = (data) => (_.has(data, 'id')) ? action(types.UPDATE_USER_GROUP, { data }) : action(types.SAVE_USER_GROUP, { data });

export const getUserGroupById = (data) => action(types.GET_USER_GROUP_BY_ID, { data });

export const fetchUsersByUserGroup = (data) => action(types.FETCH_USERS_BY_USER_GROUP, { data });

export const updateUsersInGUserGroup = (data) => action(types.UPDATE_USERS_IN_USER_GROUP, { data });

export const resetForm = () => action(types.RESET_FORM);

export const storeJsonDataForUserGroup = (data) => action(types.STORE_JSON_DATA_FOR_USER_GROUP, { data });

export const setTabIndex = (data) => action(types.SET_USER_GROUP_TAB_INDEX, { data });

export const fetchAssignUsersUnderUserGroup = (data) => action(types.ASSIGN_USERS_UNDER_USER_GROUP, { data });

export const submitAssignUsersUnderUserGroup = (data) => action(types.SUBMIT_ASSIGN_USERS_UNDER_USER_GROUP, { data });

