
const STATE_REDUCER_KEY = 'userGroup';

const TABLE_IDS = {
    LIST_USER_GROUP: 'LIST_USER_GROUP',
    ASSIGN_USERS_IN_USER_GROUP: 'ASSIGN_USERS_IN_USER_GROUP'
};

export { STATE_REDUCER_KEY, TABLE_IDS };

