import { action } from '../../common';
export const types = {
    FETCH_SUBSCRIPTION_TYPE_DETAILS: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS',
    FETCH_SUBSCRIPTION_TYPE_DETAILS_REQUEST: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_REQUEST',
    FETCH_SUBSCRIPTION_TYPE_DETAILS_SUCCESS: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_SUCCESS',
    FETCH_SUBSCRIPTION_TYPE_DETAILS_FAILURE: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_FAILURE',

    FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID',
    FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID_REQUEST: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID_REQUEST',
    FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID_SUCCESS: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID_SUCCESS',
    FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID_FAILURE: 'subscription/FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID_FAILURE',

    SAVE_SUBSCRIPTION_TYPE_DETAILS: 'subscription/SAVE_SUBSCRIPTION_TYPE_DETAILS',
    SAVE_SUBSCRIPTION_TYPE_DETAILS_REQUEST: 'subscription/SAVE_SUBSCRIPTION_TYPE_DETAILS_REQUEST',
    SAVE_SUBSCRIPTION_TYPE_DETAILS_SUCCESS: 'subscription/SAVE_SUBSCRIPTION_TYPE_DETAILS_SUCCESS',
    SAVE_SUBSCRIPTION_TYPE_DETAILS_FAILURE: 'subscription/SAVE_SUBSCRIPTION_TYPE_DETAILS_FAILURE',

    UPDATE_SUBSCRIPTION_TYPE_DETAILS: 'subscription/UPDATE_SUBSCRIPTION_TYPE_DETAILS',
    UPDATE_SUBSCRIPTION_TYPE_DETAILS_REQUEST: 'subscription/UPDATE_SUBSCRIPTION_TYPE_DETAILS_REQUEST',
    UPDATE_SUBSCRIPTION_TYPE_DETAILS_SUCCESS: 'subscription/UPDATE_SUBSCRIPTION_TYPE_DETAILS_SUCCESS',
    UPDATE_SUBSCRIPTION_TYPE_DETAILS_FAILURE: 'subscription/UPDATE_SUBSCRIPTION_TYPE_DETAILS_FAILURE',

    DELETE_SUBSCRIPTION_TYPE_DETAILS: 'subscription/DELETE_SUBSCRIPTION_TYPE_DETAILS',
    DELETE_SUBSCRIPTION_TYPE_DETAILS_REQUEST: 'subscription/DELETE_SUBSCRIPTION_TYPE_DETAILS_REQUEST',
    DELETE_SUBSCRIPTION_TYPE_DETAILS_SUCCESS: 'subscription/DELETE_SUBSCRIPTION_TYPE_DETAILS_SUCCESS',
    DELETE_SUBSCRIPTION_TYPE_DETAILS_FAILURE: 'subscription/DELETE_SUBSCRIPTION_TYPE_DETAILS_FAILURE',

    CLEAR_SUBSCRIPTION_TYPE_DETAILS_REDUCER: 'subscription/CLEAR_SUBSCRIPTION_TYPE_DETAILS_REDUCER',


    LIST_ORGANISATION_ROLE: 'subscriptions/LIST_ORGANISATION_ROLE',
    LIST_ORGANISATION_ROLE_REQUEST: 'subscriptions/LIST_ORGANISATION_ROLE_REQUEST',
    LIST_ORGANISATION_ROLE_SUCCESS: 'subscriptions/LIST_ORGANISATION_ROLE_SUCCESS',
    LIST_ORGANISATION_ROLE_FAILURE: 'subscriptions/LIST_ORGANISATION_ROLE_FAILURE',

    LIST_SUBSCRIPTION_TOPIC_ROLE: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_ROLE',
    LIST_SUBSCRIPTION_TOPIC_ROLE_REQUEST: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_ROLE_REQUEST',
    LIST_SUBSCRIPTION_TOPIC_ROLE_SUCCESS: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_ROLE_SUCCESS',
    LIST_SUBSCRIPTION_TOPIC_ROLE_FAILURE: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_ROLE_FAILURE',

    SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC: 'subscriptions/SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC',
    SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC_REQUEST: 'subscriptions/SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC_REQUEST',
    SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC_SUCCESS: 'subscriptions/SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC_SUCCESS',
    SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC_FAILURE: 'subscriptions/SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC_FAILURE',

    LIST_USER_GROUPS: 'subscriptions/LIST_USER_GROUPS',
    LIST_USER_GROUPS_REQUEST: 'subscriptions/LIST_USER_GROUPS_REQUEST',
    LIST_USER_GROUPS_SUCCESS: 'subscriptions/LIST_USER_GROUPS_SUCCESS',
    LIST_USER_GROUPS_FAILURE: 'subscriptions/LIST_USER_GROUPS_FAILURE',

    LIST_SUBSCRIPTION_TOPIC_USER_GROUP: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_USER_GROUP',
    LIST_SUBSCRIPTION_TOPIC_USER_GROUP_REQUEST: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_USER_GROUP_REQUEST',
    LIST_SUBSCRIPTION_TOPIC_USER_GROUP_SUCCESS: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_USER_GROUP_SUCCESS',
    LIST_SUBSCRIPTION_TOPIC_USER_GROUP_FAILURE: 'subscriptions/LIST_SUBSCRIPTION_TOPIC_USER_GROUP_FAILURE',

    SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC: 'subscriptions/SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC',
    SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC_REQUEST: 'subscriptions/SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC_REQUEST',
    SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC_SUCCESS: 'subscriptions/SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC_SUCCESS',
    SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC_FAILURE: 'subscriptions/SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC_FAILURE',


    LIST_HOME_POSTS: 'subscriptions/LIST_HOME_POSTS',
    LIST_HOME_POSTS_REQUEST: 'subscriptions/LIST_HOME_POSTS_REQUEST',
    LIST_HOME_POSTS_SUCCESS: 'subscriptions/LIST_HOME_POSTS_SUCCESS',
    LIST_HOME_POSTS_FAILURE: 'subscriptions/LIST_HOME_POSTS_FAILURE',

    SAVE_HOME_POST_DETAILS: 'subscription/SAVE_HOME_POST_DETAILS',
    SAVE_HOME_POST_DETAILS_REQUEST: 'subscription/SAVE_HOME_POST_DETAILS_REQUEST',
    SAVE_HOME_POST_DETAILS_SUCCESS: 'subscription/SAVE_HOME_POST_DETAILS_SUCCESS',
    SAVE_HOME_POST_DETAILS_FAILURE: 'subscription/SAVE_HOME_POST_DETAILS_FAILURE',

    UPDATE_HOME_POST_DETAILS: 'subscription/UPDATE_HOME_POST_DETAILS',
    UPDATE_HOME_POST_DETAILS_REQUEST: 'subscription/UPDATE_HOME_POST_DETAILS_REQUEST',
    UPDATE_HOME_POST_DETAILS_SUCCESS: 'subscription/UPDATE_HOME_POST_DETAILS_SUCCESS',
    UPDATE_HOME_POST_DETAILS_FAILURE: 'subscription/UPDATE_HOME_POST_DETAILS_FAILURE',

    DELETE_HOME_POST_DETAILS: 'subscription/DELETE_HOME_POST_DETAILS',
    DELETE_HOME_POST_DETAILS_REQUEST: 'subscription/DELETE_HOME_POST_DETAILS_REQUEST',
    DELETE_HOME_POST_DETAILS_SUCCESS: 'subscription/DELETE_HOME_POST_DETAILS_SUCCESS',
    DELETE_HOME_POST_DETAILS_FAILURE: 'subscription/DELETE_HOME_POST_DETAILS_FAILURE',


    FETCH_HOME_POST_BY_ID: 'subscription/FETCH_HOME_POST_BY_ID',
    FETCH_HOME_POST_BY_ID_REQUEST: 'subscription/FETCH_HOME_POST_BY_ID_REQUEST',
    FETCH_HOME_POST_BY_ID_SUCCESS: 'subscription/FETCH_HOME_POST_BY_ID_SUCCESS',
    FETCH_HOME_POST_BY_ID_FAILURE: 'subscription/FETCH_HOME_POST_BY_ID_FAILURE',

    CLEAR_HOME_POST_REDUCER: 'subscription/CLEAR_HOME_POST_REDUCER',
    CLEAR_DEFAULT_DATA: 'subscription/CLEAR_DEFAULT_REDUCER'

};
export const fetchSubscriptionTypeDetails = (data) => action(types.FETCH_SUBSCRIPTION_TYPE_DETAILS, { data });
export const saveSubscriptionTypeData = (data) => action(types.SAVE_SUBSCRIPTION_TYPE_DETAILS, { data });
export const updatesSubscriptionTypeData = (id, data) => action(types.UPDATE_SUBSCRIPTION_TYPE_DETAILS, { id, data });
export const deleteSubscriptionTypeData = (data, size, page) => action(types.DELETE_SUBSCRIPTION_TYPE_DETAILS, { data, size, page });
export const fetchSubscriptionTypeById = (data) => action(types.FETCH_SUBSCRIPTION_TYPE_DETAILS_BY_ID, { data });
export const clearSubscriptionTypeReducer = () => action(types.CLEAR_SUBSCRIPTION_TYPE_DETAILS_REDUCER);

export const listOrganizationRoles = (data) => action(types.LIST_ORGANISATION_ROLE, { data });
export const submitAssignRole = (data) => action(types.SUBMIT_ASSIGN_ROLE_TO_SUBSCRIPTION_TOPIC, { data });

export const listUserGroups = (data) => action(types.LIST_USER_GROUPS, { data });
export const submitUserGroup = (data) => action(types.SUBMIT_USER_GROUP_TO_SUBSCRIPTION_TOPIC, { data });

export const listHomePosts = (data) => action(types.LIST_HOME_POSTS, { data });
export const saveHomePostData = (data) => action(types.SAVE_HOME_POST_DETAILS, { data });
export const updatesHomePostData = (data) => action(types.UPDATE_HOME_POST_DETAILS, { data });
export const deleteHomePostData = (data) => action(types.DELETE_HOME_POST_DETAILS, { data });
export const fetchHomePostById = (data) => action(types.FETCH_HOME_POST_BY_ID, { data });
export const clearHomePostReducer = () => action(types.CLEAR_HOME_POST_REDUCER);
export const clearDefaultReducer = () => action(types.CLEAR_DEFAULT_DATA);


