import { action } from '../../common';

export const types = {
    LIST_ORGANIZATION_TYPE: 'OrganizationType/LIST_ORGANIZATION_TYPE',
    LIST_ORGANIZATION_TYPE_REQUEST: 'OrganizationType/LIST_ORGANIZATION_TYPE_REQUEST',
    LIST_ORGANIZATION_TYPE_SUCCESS: 'OrganizationType/LIST_ORGANIZATION_TYPE_SUCCESS',
    LIST_ORGANIZATION_TYPE_FAILURE: 'OrganizationType/LIST_ORGANIZATION_TYPE_FAILURE',

    SENT_ORGANIZATION_TYPE: 'OrganizationType/SENT_ORGANIZATION_TYPE',
    SENT_ORGANIZATION_TYPE_REQUEST: 'OrganizationType/SENT_ORGANIZATION_TYPE_REQUEST',
    SENT_ORGANIZATION_TYPE_SUCCESS: 'OrganizationType/SENT_ORGANIZATION_TYPE_SUCCESS',
    SENT_ORGANIZATION_TYPE_FAILURE: 'OrganizationType/SENT_ORGANIZATION_TYPE_FAILURE',

    EDIT_ORGANIZATION_TYPE: 'OrganizationType/EDIT_ORGANIZATION_TYPE',
    EDIT_ORGANIZATION_TYPE_REQUEST: 'OrganizationType/EDIT_ORGANIZATION_TYPE_REQUEST',
    EDIT_ORGANIZATION_TYPE_SUCCESS: 'OrganizationType/EDIT_ORGANIZATION_TYPE_SUCCESS',
    EDIT_ORGANIZATION_TYPE_FAILURE: 'OrganizationType/EDIT_ORGANIZATION_TYPE_FAILURE',

    GET_ORGANIZATION_TYPE_BY_ID: 'OrganizationType/GET_ORGANIZATION_TYPE_BY_ID',
    GET_ORGANIZATION_TYPE_BY_ID_REQUEST: 'OrganizationType/GET_ORGANIZATION_TYPE_BY_ID_REQUEST',
    GET_ORGANIZATION_TYPE_BY_ID_SUCCESS: 'OrganizationType/GET_ORGANIZATION_TYPE_BY_ID_SUCCESS',
    GET_ORGANIZATION_TYPE_BY_ID_FAILURE: 'OrganizationType/GET_ORGANIZATION_TYPE_BY_ID_FAILRUE',
    DELETE_ORGANIZATION_TYPE: 'OrganizationType/DELETE_ORGANIZATION_TYPE',
    DELETE_ORGANIZATION_TYPE_REQUEST: 'OrganizationType/DELETE_ORGANIZATION_TYPE_REQUEST',
    DELETE_ORGANIZATION_TYPE_SUCCESS: 'OrganizationType/DELETE_ORGANIZATION_TYPE_SUCCESS',
    DELETE_ORGANIZATION_TYPE_FAILURE: 'OrganizationType/DELETE_ORGANIZATION_TYPE_FAILURE',
    RESET_SERVICE_FORM: 'OrganizationType/RESET_SERVICE_FORM'

};

export const listOrganizationType = (data) => action(types.LIST_ORGANIZATION_TYPE, { data });

export const sentOrganizationType = (data) => action(types.SENT_ORGANIZATION_TYPE, { data });
export const editOrganizationType = (id, data) => action(types.EDIT_ORGANIZATION_TYPE, { id, data });

export const getOrganizationTypeById = (id) => action(types.GET_ORGANIZATION_TYPE_BY_ID, { id });

export const deleteOrganizationType = (data, page, size, count) => action(types.DELETE_ORGANIZATION_TYPE, { data, page, size, count });

export const resetOrganizationTypeForm = () => action(types.RESET_SERVICE_FORM);

