import { action } from '../../common';
export const types = {
    FETCH_EVENT_DETAILS: 'Event/FETCH_EVENT_DETAILS',
    FETCH_EVENT_DETAILS_REQUEST: 'Event/FETCH_EVENT_DETAILS_REQUEST',
    FETCH_EVENT_DETAILS_SUCCESS: 'Event/FETCH_EVENT_DETAILS_SUCCESS',
    FETCH_EVENT_DETAILS_FAILURE: 'Event/FETCH_EVENT_DETAILS_FAILURE',

    FETCH_EVENT_DETAILS_BY_ID: 'Event/FETCH_EVENT_DETAILS_BY_ID',
    FETCH_EVENT_DETAILS_BY_ID_REQUEST: 'Event/FETCH_EVENT_DETAILS_BY_ID_REQUEST',
    FETCH_EVENT_DETAILS_BY_ID_SUCCESS: 'Event/FETCH_EVENT_DETAILS_BY_ID_SUCCESS',
    FETCH_EVENT_DETAILS_BY_ID_FAILURE: 'Event/FETCH_EVENT_DETAILS_BY_ID_FAILURE',

    SAVE_EVENT_DETAILS: 'Event/SAVE_EVENT_DETAILS',
    SAVE_EVENT_DETAILS_REQUEST: 'Event/SAVE_EVENT_DETAILS_REQUEST',
    SAVE_EVENT_DETAILS_SUCCESS: 'Event/SAVE_EVENT_DETAILS_SUCCESS',
    SAVE_EVENT_DETAILS_FAILURE: 'Event/SAVE_EVENT_DETAILS_FAILURE',

    UPDATE_EVENT_DETAILS: 'Event/UPDATE_EVENT_DETAILS',
    UPDATE_EVENT_DETAILS_REQUEST: 'Event/UPDATE_EVENT_DETAILS_REQUEST',
    UPDATE_EVENT_DETAILS_SUCCESS: 'Event/UPDATE_EVENT_DETAILS_SUCCESS',
    UPDATE_EVENT_DETAILS_FAILURE: 'Event/UPDATE_EVENT_DETAILS_FAILURE',

    DELETE_EVENT_DETAILS: 'Event/DELETE_EVENT_DETAILS',
    DELETE_EVENT_DETAILS_REQUEST: 'Event/DELETE_EVENT_DETAILS_REQUEST',
    DELETE_EVENT_DETAILS_SUCCESS: 'Event/DELETE_EVENT_DETAILS_SUCCESS',
    DELETE_EVENT_DETAILS_FAILURE: 'Event/DELETE_EVENT_DETAILS_FAILURE',

    FETCH_ROLES_DETAILS: 'Event/FETCH_ROLES_DETAILS',
    FETCH_ROLES_DETAILS_REQUEST: 'Event/FETCH_ROLES_DETAILS_REQUEST',
    FETCH_ROLES_DETAILS_SUCCESS: 'Event/FETCH_ROLES_DETAILS_SUCCESS',
    FETCH_ROLES_DETAILS_FAILURE: 'Event/FETCH_ROLES_DETAILS_FAILURE',

    FETCH_DEFAULT_ROLES_DETAILS: 'Event/FETCH_DEFAULT_ROLES_DETAILS',
    FETCH_DEFAULT_ROLES_DETAILS_REQUEST: 'Event/FETCH_DEFAULT_ROLES_DETAILS_REQUEST',
    FETCH_DEFAULT_ROLES_DETAILS_SUCCESS: 'Event/FETCH_DEFAULT_ROLES_DETAILS_SUCCESS',
    FETCH_DEFAULT_ROLES_DETAILS_FAILURE: 'Event/FETCH_DEFAULT_ROLES_DETAILS_FAILURE',

    FETCH_USER_GROUPS_DETAILS: 'Event/FETCH_USER_GROUPS_DETAILS',
    FETCH_USER_GROUPS_DETAILS_REQUEST: 'Event/FETCH_USER_GROUPS_DETAILS_REQUEST',
    FETCH_USER_GROUPS_DETAILS_SUCCESS: 'Event/FETCH_USER_GROUPS_DETAILS_SUCCESS',
    FETCH_USER_GROUPS_DETAILS_FAILURE: 'Event/FETCH_USER_GROUPS_DETAILS_FAILURE',

    FETCH_DEFAULT_USER_GROUPS_DETAILS: 'Event/FETCH_DEFAULT_USER_GROUPS_DETAILS',
    FETCH_DEFAULT_USER_GROUPS_DETAILS_REQUEST: 'Event/FETCH_DEFAULT_USER_GROUPS_DETAILS_REQUEST',
    FETCH_DEFAULT_USER_GROUPS_DETAILS_SUCCESS: 'Event/FETCH_DEFAULT_USER_GROUPS_DETAILS_SUCCESS',
    FETCH_DEFAULT_USER_GROUPS_DETAILS_FAILURE: 'Event/FETCH_DEFAULT_USER_GROUPS_DETAILS_FAILURE',

    FETCH_EVENT_TYPE: 'Event/FETCH_EVENT_TYPE',
    FETCH_EVENT_TYPE_REQUEST: 'Event/FETCH_EVENT_TYPE_REQUEST',
    FETCH_EVENT_TYPE_SUCCESS: 'Event/FETCH_EVENT_TYPE_SUCCESS',
    FETCH_EVENT_TYPE_FAILURE: 'Event/FETCH_EVENT_TYPE_FAILURE',

    FETCH_STATE: 'Event/FETCH_STATE',
    FETCH_STATE_REQUEST: 'Event/FETCH_STATE_REQUEST',
    FETCH_STATE_SUCCESS: 'Event/FETCH_STATE_SUCCESS',
    FETCH_STATE_FAILURE: 'Event/FETCH_STATE_FAILURE',

    FETCH_DISTRICT: 'Event/FETCH_DISTRICT',
    FETCH_DISTRICT_REQUEST: 'Event/FETCH_DISTRICT_REQUEST',
    FETCH_DISTRICT_SUCCESS: 'Event/FETCH_DISTRICT_SUCCESS',
    FETCH_DISTRICT_FAILURE: 'Event/FETCH_DISTRICT_FAILURE',

    FETCH_ONLINE_PLATFORMS: 'Event/FETCH_ONLINE_PLATFORMS',
    FETCH_ONLINE_PLATFORMS_REQUEST: 'Event/FETCH_ONLINE_PLATFORMS_REQUEST',
    FETCH_ONLINE_PLATFORMS_SUCCESS: 'Event/FETCH_ONLINE_PLATFORMS_SUCCESS',
    FETCH_ONLINE_PLATFORMS_FAILURE: 'Event/FETCH_ONLINE_PLATFORMS_FAILURE',

    FETCH_LSGI_TYPE: 'Event/FETCH_LSGI_TYPE',
    FETCH_LSGI_TYPE_REQUEST: 'Event/FETCH_LSGI_TYPE_REQUEST',
    FETCH_LSGI_TYPE_SUCCESS: 'Event/FETCH_LSGI_TYPE_SUCCESS',
    FETCH_LSGI_TYPE_FAILURE: 'Event/FETCH_LSGI_TYPE_FAILURE',

    FETCH_LSGI: 'Event/FETCH_LSGI',
    FETCH_LSGI_REQUEST: 'Event/FETCH_LSGI_REQUEST',
    FETCH_LSGI_SUCCESS: 'Event/FETCH_LSGI_SUCCESS',
    FETCH_LSGI_FAILURE: 'Event/FETCH_LSGI_FAILURE',

    CLEAR_EVENT_DETAILS_REDUCER: 'Event/CLEAR_EVENT_DETAILS_REDUCER'

};
export const fetchEventDetails = (data) => action(types.FETCH_EVENT_DETAILS, { data });
export const saveEventData = (data) => action(types.SAVE_EVENT_DETAILS, { data });
export const updatesEventData = (id, data) => action(types.UPDATE_EVENT_DETAILS, { id, data });
export const deleteEventData = (data, size, page) => action(types.DELETE_EVENT_DETAILS, { data, size, page });
export const fetchEventDataById = (data) => action(types.FETCH_EVENT_DETAILS_BY_ID, { data });
export const clearEventReducer = () => action(types.CLEAR_EVENT_DETAILS_REDUCER);

export const fetchRoles = () => action(types.FETCH_ROLES_DETAILS);
export const fetchDefaultRoles = () => action(types.FETCH_DEFAULT_ROLES_DETAILS);
export const fetchUserGroups = () => action(types.FETCH_USER_GROUPS_DETAILS);
export const fetchDefaultUserGroups = () => action(types.FETCH_DEFAULT_USER_GROUPS_DETAILS);
export const fetchEventType = () => action(types.FETCH_EVENT_TYPE);

export const fetchStateList = () => action(types.FETCH_STATE);
export const fetchDistrict = (data) => action(types.FETCH_DISTRICT, { data });
export const fetchLSGIType = () => action(types.FETCH_LSGI_TYPE);
export const fetchLSGI = (lsgiTypeId, districtId) => action(types.FETCH_LSGI, { lsgiTypeId, districtId });
export const fetchOnlinePlatforms = () => action(types.FETCH_ONLINE_PLATFORMS);
