import { action } from '../../common';
export const types = {
    FETCH_DISTRICT_DETAILS: 'BasicConfig/FETCH_DISTRICT_DETAILS',
    FETCH_DISTRICT_DETAILS_REQUEST: 'BasicConfig/FETCH_DISTRICT_DETAILS_REQUEST',
    FETCH_DISTRICT_DETAILS_SUCCESS: 'BasicConfig/FETCH_DISTRICT_DETAILS_SUCCESS',
    FETCH_DISTRICT_DETAILS_FAILURE: 'BasicConfig/FETCH_DISTRICT_DETAILS_FAILURE',

    FETCH_DISTRICT_DETAILS_BY_ID: 'BasicConfig/FETCH_DISTRICT_DETAILS_BY_ID',
    FETCH_DISTRICT_DETAILS_BY_ID_REQUEST: 'BasicConfig/FETCH_DISTRICT_DETAILS_BY_ID_REQUEST',
    FETCH_DISTRICT_DETAILS_BY_ID_SUCCESS: 'BasicConfig/FETCH_DISTRICT_DETAILS_BY_ID_SUCCESS',
    FETCH_DISTRICT_DETAILS_BY_ID_FAILURE: 'BasicConfig/FETCH_DISTRICT_DETAILS_BY_ID_FAILURE',

    SAVE_DISTRICT_DETAILS: 'BasicConfig/SAVE_DISTRICT_DETAILS',
    SAVE_DISTRICT_DETAILS_REQUEST: 'BasicConfig/SAVE_DISTRICT_DETAILS_REQUEST',
    SAVE_DISTRICT_DETAILS_SUCCESS: 'BasicConfig/SAVE_DISTRICT_DETAILS_SUCCESS',
    SAVE_DISTRICT_DETAILS_FAILURE: 'BasicConfig/SAVE_DISTRICT_DETAILS_FAILURE',

    UPDATE_DISTRICT_DETAILS: 'BasicConfig/UPDATE_DISTRICT_DETAILS',
    UPDATE_DISTRICT_DETAILS_REQUEST: 'BasicConfig/UPDATE_DISTRICT_DETAILS_REQUEST',
    UPDATE_DISTRICT_DETAILS_SUCCESS: 'BasicConfig/UPDATE_DISTRICT_DETAILS_SUCCESS',
    UPDATE_DISTRICT_DETAILS_FAILURE: 'BasicConfig/UPDATE_DISTRICT_DETAILS_FAILURE',

    DELETE_DISTRICT_DETAILS: 'BasicConfig/DELETE_DISTRICT_DETAILS',
    DELETE_DISTRICT_DETAILS_REQUEST: 'BasicConfig/DELETE_DISTRICT_DETAILS_REQUEST',
    DELETE_DISTRICT_DETAILS_SUCCESS: 'BasicConfig/DELETE_DISTRICT_DETAILS_SUCCESS',
    DELETE_DISTRICT_DETAILS_FAILURE: 'BasicConfig/DELETE_DISTRICT_DETAILS_FAILURE',

    CLEAR_DISTRICT_DETAILS_REDUCER: 'BasicConfig/CLEAR_DISTRICT_DETAILS_REDUCER'

};
export const fetchDistrictDetails = (data) => action(types.FETCH_DISTRICT_DETAILS, { data });
export const saveDistrictData = (data) => action(types.SAVE_DISTRICT_DETAILS, { data });
export const updateDistrictData = (id, data) => action(types.UPDATE_DISTRICT_DETAILS, { id, data });
export const deleteDistrictData = (data, size, page) => action(types.DELETE_DISTRICT_DETAILS, { data, size, page });
export const fetchDistrictById = (data) => action(types.FETCH_DISTRICT_DETAILS_BY_ID, { data });
export const clearReducer = () => action(types.CLEAR_DISTRICT_DETAILS_REDUCER);

