import { action } from '../../common';
export const types = {
    FETCH_STATE_DETAILS: 'BasicConfig/FETCH_STATE_DETAILS',
    FETCH_STATE_DETAILS_REQUEST: 'BasicConfig/FETCH_STATE_DETAILS_REQUEST',
    FETCH_STATE_DETAILS_SUCCESS: 'BasicConfig/FETCH_STATE_DETAILS_SUCCESS',
    FETCH_STATE_DETAILS_FAILURE: 'BasicConfig/FETCH_STATE_DETAILS_FAILURE',

    FETCH_STATE_DETAILS_BY_ID: 'BasicConfig/FETCH_STATE_DETAILS_BY_ID',
    FETCH_STATE_DETAILS_BY_ID_REQUEST: 'BasicConfig/FETCH_STATE_DETAILS_BY_ID_REQUEST',
    FETCH_STATE_DETAILS_BY_ID_SUCCESS: 'BasicConfig/FETCH_STATE_DETAILS_BY_ID_SUCCESS',
    FETCH_STATE_DETAILS_BY_ID_FAILURE: 'BasicConfig/FETCH_STATE_DETAILS_BY_ID_FAILURE',

    SAVE_STATE_DETAILS: 'BasicConfig/SAVE_STATE_DETAILS',
    SAVE_STATE_DETAILS_REQUEST: 'BasicConfig/SAVE_STATE_DETAILS_REQUEST',
    SAVE_STATE_DETAILS_SUCCESS: 'BasicConfig/SAVE_STATE_DETAILS_SUCCESS',
    SAVE_STATE_DETAILS_FAILURE: 'BasicConfig/SAVE_STATE_DETAILS_FAILURE',

    UPDATE_STATE_DETAILS: 'BasicConfig/UPDATE_STATE_DETAILS',
    UPDATE_STATE_DETAILS_REQUEST: 'BasicConfig/UPDATE_STATE_DETAILS_REQUEST',
    UPDATE_STATE_DETAILS_SUCCESS: 'BasicConfig/UPDATE_STATE_DETAILS_SUCCESS',
    UPDATE_STATE_DETAILS_FAILURE: 'BasicConfig/UPDATE_STATE_DETAILS_FAILURE',

    DELETE_STATE_DETAILS: 'BasicConfig/DELETE_STATE_DETAILS',
    DELETE_STATE_DETAILS_REQUEST: 'BasicConfig/DELETE_STATE_DETAILS_REQUEST',
    DELETE_STATE_DETAILS_SUCCESS: 'BasicConfig/DELETE_STATE_DETAILS_SUCCESS',
    DELETE_STATE_DETAILS_FAILURE: 'BasicConfig/DELETE_STATE_DETAILS_FAILURE',

    CLEAR_STATE_DETAILS_REDUCER: 'BasicConfig/CLEAR_STATE_DETAILS_REDUCER'

};
export const fetchStateDetails = (data) => action(types.FETCH_STATE_DETAILS, { data });
export const saveStateData = (data) => action(types.SAVE_STATE_DETAILS, { data });
export const updatesStateData = (id, data) => action(types.UPDATE_STATE_DETAILS, { id, data });
export const deleteStateData = (data, size, page) => action(types.DELETE_STATE_DETAILS, { data, size, page });
export const fetchStateById = (data) => action(types.FETCH_STATE_DETAILS_BY_ID, { data });
export const clearStateReducer = () => action(types.CLEAR_STATE_DETAILS_REDUCER);
