import { action } from '../../common';

export const types = {
    ADD_USER: 'UserManagement/ADD_USER',
    ADD_USER_REQUEST: 'UserManagement/ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'UserManagement/ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'UserManagement/ADD_USER_FAILURE',
    UPDATE_USER_ORGANISATION: 'UserManagement/UPDATE_USER_ORGANISATION',
    UPDATE_USER_ORGANISATION_REQUEST: 'UserManagement/UPDATE_USER_ORGANISATION_REQUEST',
    UPDATE_USER_ORGANISATION_SUCCESS: 'UserManagement/UPDATE_USER_ORGANISATION_SUCCESS',
    UPDATE_USER_ORGANISATION_FAILURE: 'UserManagement/UPDATE_USER_ORGANISATION_FAILURE',

    UPDATE_USER_ROLES: 'UserManagement/UPDATE_USER_ROLES',
    UPDATE_USER_ROLES_REQUEST: 'UserManagement/UPDATE_USER_ROLES_REQUEST',
    UPDATE_USER_ROLES_SUCCESS: 'UserManagement/UPDATE_USER_ROLES_SUCCESS',
    UPDATE_USER_ROLES_FAILURE: 'UserManagement/UPDATE_USER_ROLES_FAILURE',

    UPDATE_USER_PASSWORD: 'UserManagement/UPDATE_USER_PASSWORD',
    UPDATE_USER_PASSWORD_REQUEST: 'UserManagement/UPDATE_USER_PASSWORD_REQUEST',
    UPDATE_USER_PASSWORD_SUCCESS: 'UserManagement/UPDATE_USER_PASSWORD_SUCCESS',
    UPDATE_USER_PASSWORD_FAILURE: 'UserManagement/UPDATE_USER_PASSWORD_FAILURE',

    SEARCH_USER: 'UserManagement/SEARCH_USER',
    SEARCH_USER_REQUEST: 'UserManagement/SEARCH_USER_REQUEST',
    SEARCH_USER_SUCCESS: 'UserManagement/SEARCH_USER_SUCCESS',
    SEARCH_USER_FAILURE: 'UserManagement/SEARCH_USER_FAILURE',

    GET_USER_BY_ID: 'UserManagement/GET_USER_BY_ID',
    GET_USER_BY_ID_SUCCESS: 'UserManagement/GET_USER_BY_ID_SUCCESS',
    GET_USER_BY_ID_REQUEST: 'UserManagement/GET_USER_BY_ID_REQUEST',
    GET_USER_BY_ID_FAILURE: 'UserManagement/GET_USER_BY_ID_FAILURE',

    UPDATE_USER: 'UserManagement/UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UserManagement/UPDATE_USER_SUCCESS',
    UPDATE_USER_REQUEST: 'UserManagement/UPDATE_USER_REQUEST',
    UPDATE_USER_FAILURE: 'UserManagement/UPDATE_USER_FAILURE',

    DELETE_USER: 'UserManagement/DELETE_USER',
    DELETE_USER_REQUEST: 'UserManagement/DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'UserManagement/DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'UserManagement/DELETE_USER_FAILURE',

    LIST_USER: 'UserManagement/LIST_USER',
    LIST_USER_REQUEST: 'UserManagement/LIST_USER_REQUEST',
    LIST_USER_SUCCESS: 'UserManagement/LIST_USER_SUCCESS',
    LIST_USER_FAILURE: 'UserManagement/LIST_USER_FAILURE',

    LOAD_STATE: 'UserManagement/LOAD_STATE',
    LOAD_STATE_REQUEST: 'UserManagement/LOAD_STATE_REQUEST',
    LOAD_STATE_SUCCESS: 'UserManagement/LOAD_STATE_SUCCESS',
    LOAD_STATE_FAILURE: 'UserManagement/LOAD_STATE_FAILURE',

    LOAD_DISTRICT: 'UserManagement/LOAD_DISTRICT',
    LOAD_DISTRICT_REQUEST: 'UserManagement/LOAD_DISTRICT_REQUEST',
    LOAD_DISTRICT_SUCCESS: 'UserManagement/LOAD_DISTRICT_SUCCESS',
    LOAD_DISTRICT_FAILURE: 'UserManagement/LOAD_DISTRICT_FAILURE',

    LIST_COUNTRY_CODE: 'UserManagement/LIST_COUNTRY_CODE',
    LIST_COUNTRY_CODE_SUCCESS: 'UserManagement/LIST_COUNTRY_CODE_SUCCESS',
    LIST_COUNTRY_CODE_FAILURE: 'UserManagement/LIST_COUNTRY_CODE_FAILURE',
    LIST_COUNTRY_CODE_REQUEST: 'UserManagement/LIST_COUNTRY_CODE_REQUEST',

    GET_CONTACT_DETAILS: 'UserManagement/GET_CONTACT_DETAILS',
    GET_CONTACT_DETAILS_REQUEST: 'UserManagement/GET_CONTACT_DETAILS_REQUEST',
    GET_CONTACT_DETAILS_SUCCESS: 'UserManagement/GET_CONTACT_DETAILS_SUCCESS',
    GET_CONTACT_DETAILS_FAILURE: 'UserManagement/GET_CONTACT_DETAILS_FAILURE',

    GET_ADDRESS_OF_USER: 'UserManagement/GET_ADDRESS_OF_USER',
    GET_ADDRESS_OF_USER_REQUEST: 'UserManagement/GET_ADDRESS_OF_USER_REQUEST',
    GET_ADDRESS_OF_USER_SUCCESS: 'UserManagement/GET_ADDRESS_OF_USER_SUCCESS',
    GET_ADDRESS_OF_USER_FAILURE: 'UserManagement/GET_ADDRESS_OF_USER_FAILURE',

    UPDATE_USER_ADDRESS: 'UserManagement/UPDATE_USER_ADDRESS',
    UPDATE_USER_ADDRESS_REQUEST: 'UserManagement/UPDATE_USER_ADDRESS_REQUEST',
    UPDATE_USER_ADDRESS_SUCCESS: 'UserManagement/UPDATE_USER_ADDRESS_SUCCESS',
    UPDATE_USER_ADDRESS_FAILURE: 'UserManagement/UPDATE_USER_ADDRESS_FAILURE',

    LOAD_ORGANISATION_DETAILS_WITH_USER_ID: 'UserManagement/LOAD_ORGANISATION_DETAILS_WITH_USER_ID',
    LOAD_ORGANISATION_DETAILS_WITH_USER_ID_REQUEST: 'UserManagement/LOAD_ORGANISATION_DETAILS_WITH_USER_ID_REQUEST',
    LOAD_ORGANISATION_DETAILS_WITH_USER_ID_SUCCESS: 'UserManagement/LOAD_ORGANISATION_DETAILS_WITH_USER_ID_SUCCESS',
    LOAD_ORGANISATION_DETAILS_WITH_USER_ID_FAILURE: 'UserManagement/LOAD_ORGANISATION_DETAILS_WITH_USER_ID_FAILURE',

    ASSIGN_ORGANISATION_FOR_USER_EDIT: 'UserManagement/ASSIGN_ORGANISATION_FOR_USER_EDIT',
    ASSIGN_ORGANISATION_FOR_USER_EDIT_REQUEST: 'UserManagement/ASSIGN_ORGANISATION_FOR_USER_EDIT_REQUEST',
    ASSIGN_ORGANISATION_FOR_USER_EDIT_SUCCESS: 'UserManagement/ASSIGN_ORGANISATION_FOR_USER_EDIT_SUCCESS',
    ASSIGN_ORGANISATION_FOR_USER_EDIT_FAILURE: 'UserManagement/ASSIGN_ORGANISATION_FOR_USER_EDIT_FAILURE',

    LOAD_ROLE_DETAILS_WITH_USER_ID: 'UserManagement/LOAD_ROLE_DETAILS_WITH_USER_ID',
    LOAD_ROLE_DETAILS_WITH_USER_ID_REQUEST: 'UserManagement/LOAD_ROLE_DETAILS_WITH_USER_ID_REQUEST',
    LOAD_ROLE_DETAILS_WITH_USER_ID_SUCCESS: 'UserManagement/LOAD_ROLE_DETAILS_WITH_USER_ID_SUCCESS',
    LOAD_ROLE_DETAILS_WITH_USER_ID_FAILURE: 'UserManagement/LOAD_ROLE_DETAILS_WITH_USER_ID_FAILURE',

    ASSIGN_ROLE_FOR_USER_EDIT: 'UserManagement/ASSIGN_ROLE_FOR_USER_EDIT',
    ASSIGN_ROLE_FOR_USER_EDIT_REQUEST: 'UserManagement/ASSIGN_ROLE_FOR_USER_EDIT_REQUEST',
    ASSIGN_ROLE_FOR_USER_EDIT_SUCCESS: 'UserManagement/ASSIGN_ROLE_FOR_USER_EDIT_SUCCESS',
    ASSIGN_ROLE_FOR_USER_EDIT_FAILURE: 'UserManagement/ASSIGN_ROLE_FOR_USER_EDIT_FAILURE',

    LOAD_USER_GROUP_DETAILS_WITH_USER_ID: 'UserManagement/LOAD_USER_GROUP_DETAILS_WITH_USER_ID',
    LOAD_USER_GROUP_DETAILS_WITH_USER_ID_REQUEST: 'UserManagement/LOAD_USER_GROUP_DETAILS_WITH_USER_ID_REQUEST',
    LOAD_USER_GROUP_DETAILS_WITH_USER_ID_SUCCESS: 'UserManagement/LOAD_USER_GROUP_DETAILS_WITH_USER_ID_SUCCESS',
    LOAD_USER_GROUP_DETAILS_WITH_USER_ID_FAILURE: 'UserManagement/LOAD_USER_GROUP_DETAILS_WITH_USER_ID_FAILURE',

    UPDATE_USER_GROUP_WITH_USER_ID: 'UserManagement/UPDATE_USER_GROUP_WITH_USER_ID',
    UPDATE_USER_GROUP_WITH_USER_ID_SUCCESS: 'UserManagement/UPDATE_USER_GROUP_WITH_USER_ID_SUCCESS',
    UPDATE_USER_GROUP_WITH_USER_ID_REQUEST: 'UserManagement/UPDATE_USER_GROUP_WITH_USER_ID_REQUEST',
    UPDATE_USER_GROUP_WITH_USER_ID_FAILURE: 'UserManagement/UPDATE_USER_GROUP_WITH_USER_ID_FAILURE',

    EDIT_USER_BASIC_DETAILS: 'UserManagement/EDIT_USER_BASIC_DETAILS',
    EDIT_USER_BASIC_DETAILS_REQUEST: 'UserManagement/EDIT_USER_BASIC_DETAILS_REQUEST',
    EDIT_USER_BASIC_DETAILS_SUCCESS: 'UserManagement/EDIT_USER_BASIC_DETAILS_SUCCESS',
    EDIT_USER_BASIC_DETAILS_FAILURE: 'UserManagement/EDIT_USER_BASIC_DETAILS_FAILURE',

    EDIT_USER_CONTACT: 'UserManagement/EDIT_USER_CONTACT',
    EDIT_USER_CONTACT_REQUEST: 'UserManagement/EDIT_USER_CONTACT_REQUEST',
    EDIT_USER_CONTACT_SUCCESS: 'UserManagement/EDIT_USER_CONTACT_SUCCESS',
    EDIT_USER_CONTACT_FAILURE: 'UserManagement/EDIT_USER_CONTACT_FAILURE',

    ADD_MULTIPLE_ORGANISATION: 'UserManagement/ADD_MULTIPLE_ORGANISATION',
    SET_CHECK_VALUE: 'UserManagement/SET_CHECK_VALUE',
    SET_USER_FOR_EDIT: 'UserManagement/SET_USER_FOR_EDIT',
    REMOVE_SINGLE_USER_DATA: 'UserManagement/REMOVE_SINGLE_USER_DATA',

    GET_USER_TYPE: 'UserManagement/GET_USER_TYPE',
    GET_USER_TYPE_REQUEST: 'UserManagement/GET_USER_TYPE_REQUEST',
    GET_USER_TYPE_SUCCESS: 'UserManagement/GET_USER_TYPE_SUCCESS',
    GET_USER_TYPE_FAILURE: 'UserManagement/GET_USER_TYPE_FAILURE',

    FETCH_INITIAL_PAGEBLE_USERS: 'UserManagement/FETCH_INITIAL_PAGEBLE_USERS',
    FETCH_INITIAL_PAGEBLE_USERS_REQUEST: 'UserManagement/FETCH_INITIAL_PAGEBLE_USERS_REQUEST',
    FETCH_INITIAL_PAGEBLE_USERS_SUCCESS: 'UserManagement/FETCH_INITIAL_PAGEBLE_USERS_SUCCESS',
    FETCH_INITIAL_PAGEBLE_USERS_FAILURE: 'UserManagement/FETCH_INITIAL_PAGEBLE_USERS_FAILURE',

    RESET_USER_CREATION_FORM: 'UserManagement/RESET_USER_CREATION_FORM',

    STORE_JSON_DATA_FOR_USER: 'UserManagement/STORE_JSON_DATA_FOR_USER',

    SET_TAB_INDEX_FOR_USER: 'UserManagement/SET_TAB_INDEX_FOR_USER',

    LIST_DISTRICTS_FOR_ADDRESS: 'user/LIST_DISTRICTS_FOR_ADDRESS',
    LIST_DISTRICTS_FOR_ADDRESS_REQUEST: 'user/LIST_DISTRICTS_FOR_ADDRESS_REQUEST',
    LIST_DISTRICTS_FOR_ADDRESS_SUCCESS: 'user/LIST_DISTRICTS_FOR_ADDRESS_SUCCESS',
    LIST_DISTRICTS_FOR_ADDRESS_FAILURE: 'user/LIST_DISTRICTS_FOR_ADDRESS_FAILURE',


    SET_DISTRICTS_FOR_ADDRESS: 'user/SET_DISTRICTS_FOR_ADDRESS',

    FETCH_ASSIGN_ORGANIZATION_FOR_USERS: 'User/FETCH_ASSIGN_ORGANIZATION_FOR_USERS',
    FETCH_ASSIGN_ORGANIZATION_FOR_USERS_REQUEST: 'User/FETCH_ASSIGN_ORGANIZATION_FOR_USERS_REQUEST',
    FETCH_ASSIGN_ORGANIZATION_FOR_USERS_SUCCESS: 'User/FETCH_ASSIGN_ORGANIZATION_FOR_USERS_SUCCES',
    FETCH_ASSIGN_ORGANIZATION_FOR_USERS_FAILURE: 'User/FETCH_ASSIGN_ORGANIZATION_FOR_USERS_FAILURE',

    SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER: 'User/SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER',
    SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER_REQUEST: 'User/SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER_REQUEST',
    SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER_SUCCESS: 'User/SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER_SUCCESS',
    SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER_FAILURE: 'User/SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER_FAILURE',

    FETCH_ASSIGN_ROLE_UNDER_USER: 'User/FETCH_ASSIGN_ROLE_UNDER_USER',
    FETCH_ASSIGN_ROLE_UNDER_USER_REQUEST: 'User/FETCH_ASSIGN_ROLE_UNDER_USER_REQUEST',
    FETCH_ASSIGN_ROLE_UNDER_USER_SUCCESS: 'User/FETCH_ASSIGN_ROLE_UNDER_USER_SUCCESS',
    FETCH_ASSIGN_ROLE_UNDER_USER_FAILURE: 'User/FETCH_ASSIGN_ROLE_UNDER_USER_FAILURE',

    SUBMIT_ASSIGN_ROLE_UNDER_USER: 'User/SUBMIT_ASSIGN_ROLE_UNDER_USER',
    SUBMIT_ASSIGN_ROLE_UNDER_USER_REQUEST: 'User/SUBMIT_ASSIGN_ROLE_UNDER_USER_REQUEST',
    SUBMIT_ASSIGN_ROLE_UNDER_USER_SUCCESS: 'User/SUBMIT_ASSIGN_ROLE_UNDER_USER_SUCCESS',
    SUBMIT_ASSIGN_ROLE_UNDER_USER_FAILURE: 'User/SUBMIT_ASSIGN_ROLE_UNDER_USER_FAILURE',

    FETCH_ASSIGN_USER_GROUP_UNDER_USER: 'User/FETCH_ASSIGN_USER_GROUP_UNDER_USER',
    FETCH_ASSIGN_USER_GROUP_UNDER_USER_REQUEST: 'User/FETCH_ASSIGN_USER_GROUP_UNDER_USER_REQUEST',
    FETCH_ASSIGN_USER_GROUP_UNDER_USER_SUCCESS: 'User/FETCH_ASSIGN_USER_GROUP_UNDER_USER_SUCCESS',
    FETCH_ASSIGN_USER_GROUP_UNDER_USER_FAILURE: 'User/FETCH_ASSIGN_USER_GROUP_UNDER_USER_FAILURE',

    SUBMIT_ASSIGN_USER_GROUP_UNDER_USER: 'User/SUBMIT_ASSIGN_USER_GROUP_UNDER_USER',
    SUBMIT_ASSIGN_USER_GROUP_UNDER_USER_REQUEST: 'User/SUBMIT_ASSIGN_USER_GROUP_UNDER_USER_REQUEST',
    SUBMIT_ASSIGN_USER_GROUP_UNDER_USER_SUCCESS: 'User/SUBMIT_ASSIGN_USER_GROUP_UNDER_USER_SUCCESS',
    SUBMIT_ASSIGN_USER_GROUP_UNDER_USER_FAILURE: 'User/SUBMIT_ASSIGN_USER_GROUP_UNDER_USER_FAILURE',

    LIST_GENDER: 'User/LIST_GENDER',
    LIST_GENDER_REQUEST: 'User/LIST_GENDER_REQUEST',
    LIST_GENDER_SUCCESS: 'User/LIST_GENDER_SUCCESS',
    LIST_GENDER_FAILURE: 'User/LIST_GENDER_FAILURE'
};


export const addUser = (data) => action(types.ADD_USER, { data });

export const getUserById = (id) => action(types.GET_USER_BY_ID, { id });

export const updateUser = (id, data) => action(types.UPDATE_USER, { id, data });

export const updateUserOrganisation = (id, data) => action(types.UPDATE_USER_ORGANISATION, { id, data });

export const updateUserRoles = (id, data) => action(types.UPDATE_USER_ROLES, { id, data });

export const changePassword = (data) => action(types.UPDATE_USER_PASSWORD, { data });

export const searchUser = (data) => action(types.SEARCH_USER, { data });

export const listUser = (data) => action(types.LIST_USER, { data });

export const deleteUser = (data, page, size, count) => action(types.DELETE_USER, { data, page, size, count });

export const loadState = () => action(types.LOAD_STATE);


export const loadDistricts = (data) => action(types.LIST_DISTRICTS_FOR_ADDRESS, { data });
export const setDistrictsForAddress = (data) => action(types.SET_DISTRICTS_FOR_ADDRESS, { data });


export const loadDistrict = (stateId) => action(types.LOAD_DISTRICT, { stateId });
export const loadGender = () => action(types.LIST_GENDER);


export const setCheckedValue = (checkedValue) => action(types.SET_CHECK_VALUE, { checkedValue });

export const listCountryCode = () => action(types.LIST_COUNTRY_CODE);

export const addMultpleOrganisation = () => action(types.ADD_MULTIPLE_ORGANISATION);

export const addContactDetails = (data) => action(types.ADD_CONTACT_DETAILS, { data });

export const setUserForEdit = (data) => action(types.SET_USER_FOR_EDIT, { data });

export const removeSingleUserData = () => action(types.REMOVE_SINGLE_USER_DATA);

export const updateAddress = (id, data) => action(types.UPDATE_USER_ADDRESS, { id, data });

export const getAddressOfTheUser = (id) => action(types.GET_ADDRESS_OF_USER, { id });

export const loadOrganisationListForUser = (id) => action(types.LOAD_ORGANISATION_DETAILS_WITH_USER_ID, { id });

export const updateUserOrganizationMapping = (id, data) => action(types.ASSIGN_ORGANISATION_FOR_USER_EDIT, { id, data });

export const loadRoleListForUser = (id) => action(types.LOAD_ROLE_DETAILS_WITH_USER_ID, { id });

export const updateUserRoleMapping = (id, data) => action(types.ASSIGN_ROLE_FOR_USER_EDIT, { id, data });

export const loadUserGroupListListForUser = (id) => action(types.LOAD_USER_GROUP_DETAILS_WITH_USER_ID, { id });

export const updateUserUserGroupMapping = (id, data) => action(types.UPDATE_USER_GROUP_WITH_USER_ID, { id, data });

export const edituserBasicDetails = (id, data) => action(types.EDIT_USER_BASIC_DETAILS, { id, data });

export const listContactDetails = (id) => action(types.GET_CONTACT_DETAILS, { id });

export const editContactDetails = (id, data) => action(types.EDIT_USER_CONTACT, { id, data });

export const getUserTypes = () => action(types.GET_USER_TYPE);

export const fetchInitialUser = () => action(types.FETCH_INITIAL_PAGEBLE_USERS);

export const resetUserCreationForm = () => action(types.RESET_USER_CREATION_FORM);
export const storeJsonDataForUser = (data) => action(types.STORE_JSON_DATA_FOR_USER, { data });

export const setTabIndexForUser = (data) => action(types.SET_TAB_INDEX_FOR_USER, { data });

export const fetchAssignOrganizationForUsers = (data) => action(types.FETCH_ASSIGN_ORGANIZATION_FOR_USERS, { data });

export const submitAssignOrganizationUnderUser = (data) => action(types.SUBMIT_ASSIGN_ORGANIZATION_UNDER_USER, { data });

export const fetchAssignRoleForUsers = (data) => action(types.FETCH_ASSIGN_ROLE_UNDER_USER, { data });

export const submitAssignRoleUnderUser = (data) => action(types.SUBMIT_ASSIGN_ROLE_UNDER_USER, { data });

export const fetchAssignUserGroupForUsers = (data) => action(types.FETCH_ASSIGN_USER_GROUP_UNDER_USER, { data });

export const submitAssignUserGroupUnderUser = (data) => action(types.SUBMIT_ASSIGN_USER_GROUP_UNDER_USER, { data });

