import { action } from '../../common';
export const types = {
    FETCH_CONTENT_DETAILS: 'Content/FETCH_CONTENT_DETAILS',
    FETCH_CONTENT_DETAILS_REQUEST: 'Content/FETCH_CONTENT_DETAILS_REQUEST',
    FETCH_CONTENT_DETAILS_SUCCESS: 'Content/FETCH_CONTENT_DETAILS_SUCCESS',
    FETCH_CONTENT_DETAILS_FAILURE: 'Content/FETCH_CONTENT_DETAILS_FAILURE',

    FETCH_CONTENT_DETAILS_BY_ID: 'Content/FETCH_CONTENT_DETAILS_BY_ID',
    FETCH_CONTENT_DETAILS_BY_ID_REQUEST: 'Content/FETCH_CONTENT_DETAILS_BY_ID_REQUEST',
    FETCH_CONTENT_DETAILS_BY_ID_SUCCESS: 'Content/FETCH_CONTENT_DETAILS_BY_ID_SUCCESS',
    FETCH_CONTENT_DETAILS_BY_ID_FAILURE: 'Content/FETCH_CONTENT_DETAILS_BY_ID_FAILURE',

    SAVE_CONTENT_DETAILS: 'Content/SAVE_CONTENT_DETAILS',
    SAVE_CONTENT_DETAILS_REQUEST: 'Content/SAVE_CONTENT_DETAILS_REQUEST',
    SAVE_CONTENT_DETAILS_SUCCESS: 'Content/SAVE_CONTENT_DETAILS_SUCCESS',
    SAVE_CONTENT_DETAILS_FAILURE: 'Content/SAVE_CONTENT_DETAILS_FAILURE',

    GET_ROLE_FOR_CONTENT: 'Content/GET_ROLE_FOR_CONTENT',
    GET_ROLE_FOR_CONTENT_REQUEST: 'Content/GET_ROLE_FOR_CONTENT_REQUEST',
    GET_ROLE_FOR_CONTENT_SUCCESS: 'Content/GET_ROLE_FOR_CONTENT_SUCCESS',
    GET_ROLE_FOR_CONTENT_FAILURE: 'Content/GET_ROLE_FOR_CONTENT_FAILURE',

    GET_DEFAULT_ROLE_FOR_CONTENT: 'Content/GET_DEFAULT_ROLE_FOR_CONTENT',
    GET_DEFAULT_ROLE_FOR_CONTENT_REQUEST: 'Content/GET_DEFAULT_ROLE_FOR_CONTENT_REQUEST',
    GET_DEFAULT_ROLE_FOR_CONTENT_SUCCESS: 'Content/GET_DEFAULT_ROLE_FOR_CONTENT_SUCCESS',
    GET_DEFAULT_ROLE_FOR_CONTENT_FAILURE: 'Content/GET_DEFAULT_ROLE_FOR_CONTENT_FAILURE',

    GET_USER_GROUP_FOR_CONTENT: 'Content/GET_USER_GROUP_FOR_CONTENT',
    GET_USER_GROUP_FOR_CONTENT_REQUEST: 'Content/GET_USER_GROUP_FOR_CONTENT_REQUEST',
    GET_USER_GROUP_FOR_CONTENT_SUCCESS: 'Content/GET_USER_GROUP_FOR_CONTENT_SUCCESS',
    GET_USER_GROUP_FOR_CONTENT_FAILURE: 'Content/GET_USER_GROUP_FOR_CONTENT_FAILURE',

    GET_DEFAULT_USER_GROUP_FOR_CONTENT: 'Content/GET_DEFAULT-_USER_GROUP_FOR_CONTENT',
    GET_DEFAULT_USER_GROUP_FOR_CONTENT_REQUEST: 'Content/GET_DEFAULT_USER_GROUP_FOR_CONTENT_REQUEST',
    GET_DEFAULT_USER_GROUP_FOR_CONTENT_SUCCESS: 'Content/GET_DEFAULT_USER_GROUP_FOR_CONTENT_SUCCESS',
    GET_DEFAULT_USER_GROUP_FOR_CONTENT_FAILURE: 'Content/GET_DEFAULT_USER_GROUP_FOR_CONTENT_FAILURE',

    UPDATE_CONTENT_DETAILS: 'Content/UPDATE_CONTENT_DETAILS',
    UPDATE_CONTENT_DETAILS_REQUEST: 'Content/UPDATE_CONTENT_DETAILS_REQUEST',
    UPDATE_CONTENT_DETAILS_SUCCESS: 'Content/UPDATE_CONTENT_DETAILS_SUCCESS',
    UPDATE_CONTENT_DETAILS_FAILURE: 'Content/UPDATE_CONTENT_DETAILS_FAILURE',

    DELETE_CONTENT_DETAILS: 'Content/DELETE_CONTENT_DETAILS',
    DELETE_CONTENT_DETAILS_REQUEST: 'Content/DELETE_CONTENT_DETAILS_REQUEST',
    DELETE_CONTENT_DETAILS_SUCCESS: 'Content/DELETE_CONTENT_DETAILS_SUCCESS',
    DELETE_CONTENT_DETAILS_FAILURE: 'Content/DELETE_CONTENT_DETAILS_FAILURE',

    CLEAR_CONTENT_DETAILS_REDUCER: 'Content/CLEAR_CONTENT_DETAILS_REDUCER'

};
export const fetchContentDetails = (data) => action(types.FETCH_CONTENT_DETAILS, { data });
export const saveContentData = (data) => action(types.SAVE_CONTENT_DETAILS, { data });
export const updatesContentData = (data) => action(types.UPDATE_CONTENT_DETAILS, { data });
export const deleteContentData = (data, size, page) => action(types.DELETE_CONTENT_DETAILS, { data, size, page });
export const fetchContentDataById = (data) => action(types.FETCH_CONTENT_DETAILS_BY_ID, { data });
export const clearContentReducer = () => action(types.CLEAR_CONTENT_DETAILS_REDUCER);
export const getAllRolesForContent = () => action(types.GET_ROLE_FOR_CONTENT);

export const getDefaultRolesForContent = () => action(types.GET_DEFAULT_ROLE_FOR_CONTENT);
export const getDefaultUserGroupForContent = () => action(types.GET_DEFAULT_USER_GROUP_FOR_CONTENT);

export const getAllUserGroupForContent = () => action(types.GET_USER_GROUP_FOR_CONTENT);


