import { action } from '../../common';
export const types = {
    FETCH_BLOCK_PANCHAYATH_DETAILS: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS',
    FETCH_BLOCK_PANCHAYATH_DETAILS_REQUEST: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_REQUEST',
    FETCH_BLOCK_PANCHAYATH_DETAILS_SUCCESS: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_SUCCESS',
    FETCH_BLOCK_PANCHAYATH_DETAILS_FAILURE: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_FAILURE',

    FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID',
    FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID_REQUEST: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID_REQUEST',
    FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID_SUCCESS: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID_SUCCESS',
    FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID_FAILURE: 'BasicConfig/FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID_FAILURE',

    SAVE_BLOCK_PANCHAYATH_DETAILS: 'BasicConfig/SAVE_BLOCK_PANCHAYATH_DETAILS',
    SAVE_BLOCK_PANCHAYATH_DETAILS_REQUEST: 'BasicConfig/SAVE_BLOCK_PANCHAYATH_DETAILS_REQUEST',
    SAVE_BLOCK_PANCHAYATH_DETAILS_SUCCESS: 'BasicConfig/SAVE_BLOCK_PANCHAYATH_DETAILS_SUCCESS',
    SAVE_BLOCK_PANCHAYATH_DETAILS_FAILURE: 'BasicConfig/SAVE_BLOCK_PANCHAYATH_DETAILS_FAILURE',

    UPDATE_BLOCK_PANCHAYATH_DETAILS: 'BasicConfig/UPDATE_BLOCK_PANCHAYATH_DETAILS',
    UPDATE_BLOCK_PANCHAYATH_DETAILS_REQUEST: 'BasicConfig/UPDATE_BLOCK_PANCHAYATH_DETAILS_REQUEST',
    UPDATE_BLOCK_PANCHAYATH_DETAILS_SUCCESS: 'BasicConfig/UPDATE_BLOCK_PANCHAYATH_DETAILS_SUCCESS',
    UPDATE_BLOCK_PANCHAYATH_DETAILS_FAILURE: 'BasicConfig/UPDATE_BLOCK_PANCHAYATH_DETAILS_FAILURE',

    LIST_DISTRICT_LIST_BY_STATE: 'BasicConfig/LIST_DISTRICT_LIST_BY_STATE',
    LIST_DISTRICT_LIST_BY_STATE_REQUEST: 'BasicConfig/LIST_DISTRICT_LIST_BY_STATE_REQUEST',
    LIST_DISTRICT_LIST_BY_STATE_SUCCESS: 'BasicConfig/LIST_DISTRICT_LIST_BY_STATE_SUCCESS',
    LIST_DISTRICT_LIST_BY_STATE_FAILURE: 'BasicConfig/LIST_DISTRICT_LIST_BY_STATE_FAILURE',

    DELETE_BLOCK_PANCHAYATH_DETAILS: 'BasicConfig/DELETE_BLOCK_PANCHAYATH_DETAILS',
    DELETE_BLOCK_PANCHAYATH_DETAILS_REQUEST: 'BasicConfig/DELETE_BLOCK_PANCHAYATH_DETAILS_REQUEST',
    DELETE_BLOCK_PANCHAYATH_DETAILS_SUCCESS: 'BasicConfig/DELETE_BLOCK_PANCHAYATH_DETAILS_SUCCESS',
    DELETE_BLOCK_PANCHAYATH_DETAILS_FAILURE: 'BasicConfig/DELETE_BLOCK_PANCHAYATH_DETAILS_FAILURE',

    CLEAR_BLOCK_PANCHAYATH_DETAILS_REDUCER: 'BasicConfig/CLEAR_BLOCK_PANCHAYATH_DETAILS_REDUCER'
};
export const fetchBlockPanchayathDetails = (data) => action(types.FETCH_BLOCK_PANCHAYATH_DETAILS, { data });
export const saveBlockPanchayathData = (data) => action(types.SAVE_BLOCK_PANCHAYATH_DETAILS, { data });
export const updateBlockPanchayathData = (id, data) => action(types.UPDATE_BLOCK_PANCHAYATH_DETAILS, { id, data });
export const deleteBlockPanchayathData = (data, size, page) => action(types.DELETE_BLOCK_PANCHAYATH_DETAILS, { data, size, page });
export const fetchBlockPanchayathById = (data) => action(types.FETCH_BLOCK_PANCHAYATH_DETAILS_BY_ID, { data });
export const fetchDistrictByStateId = (data) => action(types.LIST_DISTRICT_LIST_BY_STATE, { data });
export const clearReducer = () => action(types.CLEAR_BLOCK_PANCHAYATH_DETAILS_REDUCER);

