import { action } from '../../common';

export const types = {
    ORGANIZATION_COMMON_STATE_REQUEST: 'Organization/COMMON_STATE_REQUEST',
    ORGANIZATION_COMMON_STATE: 'Organization/COMMON_STATE',
    ORGANIZATION_COMMON_STATE_SUCCESS: 'Organization/COMMON_STATE_SUCCESS',
    ORGANIZATION_COMMON_STATE_FAILURE: 'Organization/COMMON_STATE_FAILURE',

    LOAD_DISTRICTS: 'Organization/COMMON_DISTRICT',
    LOAD_DISTRICTS_REQUEST: 'Organization/COMMON_DISTRICT_REQUEST',
    LOAD_DISTRICTS_SUCCESS: 'Organization/COMMON_DISTRICT_SUCCESS',
    LOAD_DISTRICTS_FAILURE: 'Organization/COMMON_DISTRICT_FAILURE',

    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH: 'Organization/COMMON_DISTRICT_PANCHAYATH',
    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH_REQUEST: 'Organization/COMMON_DISTRICT_PANCHAYATH_REQUEST',
    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH_SUCCESS: 'Organization/COMMON_DISTRICT_PANCHAYATH_SUCCESS',
    ORGANIZATION_COMMON_DISTRICT_PANCHAYATH_FAILURE: 'Organization/COMMON_DISTRICT_PANCHAYATH_FAILURE',

    ORGANIZATION_COMMON_BLOCK_PANCHAYATH: 'Organization/COMMON_BLOCK_PANCHAYATH',
    ORGANIZATION_COMMON_BLOCK_PANCHAYATH_REQUEST: 'Organization/COMMON_BLOCK_PANCHAYATH_REQUEST',
    ORGANIZATION_COMMON_BLOCK_PANCHAYATH_SUCCESS: 'Organization/COMMON_BLOCK_PANCHAYATH_SUCCESS',
    ORGANIZATION_COMMON_BLOCK_PANCHAYATH_FAILURE: 'Organization/COMMON_BLOCK_PANCHAYATH_FAILURE',

    LOAD_LSGIS: 'Organization/COMMON_LSGI',
    LOAD_LSGIS_REQUEST: 'Organization/COMMON_LSGI_REQUEST',
    LOAD_LSGIS_SUCCESS: 'Organization/COMMON_LSGI_SUCCESS',
    LOAD_LSGIS_FAILURE: 'Organization/COMMON_LSGI_FAILURE',

    LIST_ORGANISATION: 'Organization/LIST_ORGANISATION',
    LIST_ORGANISATION_REQUEST: 'Organization/LIST_ORGANISATION_REQUEST',
    LIST_ORGANISATION_SUCCESS: 'Organization/LIST_ORGANISATION_SUCCESS',
    LIST_ORGANISATION_FAILURE: 'Organization/LIST_ORGANISATION_FAILURE',

    SAVE_ORGANIZATION: 'Organization/SAVE_ORGANIZATION',
    SAVE_ORGANIZATION_REQUEST: 'Organization/SAVE_ORGANIZATION_REQUEST',
    SAVE_ORGANIZATION_SUCCESS: 'Organization/SAVE_ORGANIZATION_SUCCESS',
    SAVE_ORGANIZATION_FAILED: 'Organization/SAVE_ORGANIZATION_FAILED',

    UPDATE_ORGANIZATION: 'Organization/UPDATE_ORGANIZATION',
    UPDATE_ORGANIZATION_REQUEST: 'Organization/UPDATE_ORGANIZATION_REQUEST',
    UPDATE_ORGANIZATION_SUCCESS: 'Organization/UPDATE_ORGANIZATION_SUCCESS',
    UPDATE_ORGANIZATION_FAILED: 'Organization/UPDATE_ORGANIZATION_FAILED',

    FETCH_ORGANIZATION_DETAILS: 'Organization/FETCH_ORGANIZATION_DETAILS',
    FETCH_ORGANIZATION_DETAILS_REQUEST: 'Organization/FETCH_ORGANIZATION_DETAILS_REQUEST',
    FETCH_ORGANIZATION_DETAILS_SUCCESS: 'Organization/FETCH_ORGANIZATION_DETAILS_SUCCESS',
    FETCH_ORGANIZATION_DETAILS_FAILURE: 'Organization/FETCH_ORGANIZATION_DETAILS_FAILURE',

    DELETE_ORGANISATION: 'Organization/DELETE_ORGANISATION',
    DELETE_ORGANISATION_REQUEST: 'Organization/DELETE_ORGANISATION_REQUEST',
    DELETE_ORGANISATION_SUCCESS: 'Organization/DELETE_ORGANISATION_SUCCESS',
    DELETE_ORGANISATION_FAILURE: 'Organization/DELETE_ORGANISATION_FAILURE',

    LOAD_PARENT_ORGANIZATIONS: 'Organization/LOAD_PARENT_ORGANIZATIONS',
    LOAD_PARENT_ORGANIZATIONS_REQUEST: 'Organization/LOAD_PARENT_ORGANIZATIONS_REQUEST',
    LOAD_PARENT_ORGANIZATIONS_SUCCESS: 'Organization/LOAD_PARENT_ORGANIZATIONS_SUCCESS',
    LOAD_PARENT_ORGANIZATIONS_FAILED: 'Organization/LOAD_PARENT_ORGANIZATIONS_FAILED',

    LOAD_ORGANIZATION_TYPES: 'Organization/LOAD_ORGANIZATION_TYPES',
    LOAD_ORGANIZATION_TYPES_REQUEST: 'Organization/LOAD_ORGANIZATION_TYPES_REQUEST',
    LOAD_ORGANIZATION_TYPES_SUCCESS: 'Organization/LOAD_ORGANIZATION_TYPES_SUCCESS',
    LOAD_ORGANIZATION_TYPES_FAILED: 'Organization/LOAD_ORGANIZATION_TYPES_FAILED',

    LOAD_LSGI_TYPES: 'Organization/LOAD_LSGI_TYPES',
    LOAD_LSGI_TYPES_REQUEST: 'Organization/LOAD_LSGI_TYPES_REQUEST',
    LOAD_LSGI_TYPES_SUCCESS: 'Organization/LOAD_LSGI_TYPES_SUCCESS',
    LOAD_LSGI_TYPES_FAILED: 'Organization/LOAD_LSGI_TYPES_FAILED',

    SET_TAB_INDEX: 'Organizations/SET_TAB_INDEX',

    FETCH_ORGANIZATION_ASSIGN_USERS: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS',
    FETCH_ORGANIZATION_ASSIGN_USERS_REQUEST: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS_REQUEST',
    FETCH_ORGANIZATION_ASSIGN_USERS_SUCCESS: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS_SUCCESS',
    FETCH_ORGANIZATION_ASSIGN_USERS_FAILURE: 'Organization/FETCH_ORGANIZATION_ASSIGN_USERS_FAILURE',

    UPDATE_CHK_USER_ORGANIZATION: 'Organization/UPDATE_CHK_USER_ORGANIZATION',
    UPDATE_CHK_USER_ORGANIZATION_REQUEST: 'Organization/UPDATE_CHK_USER_ORGANIZATION_REQUEST',
    UPDATE_CHK_USER_ORGANIZATION_SUCCESS: 'Organization/UPDATE_CHK_USER_ORGANIZATION_SUCCESS',
    UPDATE_CHK_USER_ORGANIZATION_FAILURE: 'Organization/UPDATE_CHK_USER_ORGANIZATION_FAILURE',

    LOAD_ORGANIZATION_ROLE_TYPES: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES',
    LOAD_ORGANIZATION_ROLE_TYPES_REQUEST: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES_REQUEST',
    LOAD_ORGANIZATION_ROLE_TYPES_SUCCESS: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES_SUCCESS',
    LOAD_ORGANIZATION_ROLE_TYPES_FAILED: 'Organization/LOAD_ORGANIZATION_ROLE_TYPES_FAILED',

    SET_ORGANIZATION_ROLE_TYPES: 'Organization/SET_ORGANIZATION_ROLE_TYPES',

    FETCH_ASSIGN_ROLE_IN_ORG: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG',
    FETCH_ASSIGN_ROLE_IN_ORG_REQUEST: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG_REQUEST',
    FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS',
    FETCH_ASSIGN_ROLE_IN_ORG_FAILURE: 'Organization/FETCH_ASSIGN_ROLE_IN_ORG_FAILURE',

    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG',
    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_REQUEST: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_REQUEST',
    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_SUCCESS',
    SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_FAILURE: 'Organization/SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG_FAILURE',

    FETCH_MODULES_FOR_CHK: 'Organization/FETCH_MODULES_FOR_CHK',
    FETCH_MODULES_FOR_CHK_REQUEST: 'Organization/FETCH_MODULES_FOR_CHK_REQUEST',
    FETCH_MODULES_FOR_CHK_SUCCESS: 'Organization/FETCH_MODULES_FOR_CHK_SUCCESS',
    FETCH_MODULES_FOR_CHK_FAILURE: 'Organization/FETCH_MODULES_FOR_CHK_FAILURE',

    SAVE_MODULES_FOR_CHK: 'Organization/SAVE_MODULES_FOR_CHK',
    SAVE_MODULES_FOR_CHK_REQUEST: 'Organization/SAVE_MODULES_FOR_CHK_REQUEST',
    SAVE_MODULES_FOR_CHK_SUCCESS: 'Organization/SAVE_MODULES_FOR_CHK_SUCCESS',
    SAVE_MODULES_FOR_CHK_FAILURE: 'Organization/SAVE_MODULES_FOR_CHK_FAILURE',
    CLEAR_ASSIGNED_CHECKED_LIST: 'Organization/CLEAR_ASSIGNED_CHECKED_LIST',

    FETCH_ROLESLIST_FOR_MODULE: 'Organization/FETCH_ROLESLIST_FOR_MODULE',
    FETCH_ROLESLIST_FOR_MODULE_REQUEST: 'Organization/FETCH_ROLESLIST_FOR_MODULE_REQUEST',
    FETCH_ROLESLIST_FOR_MODULE_SUCCESS: 'Organization/FETCH_ROLESLIST_FOR_MODULE_SUCCESS',
    FETCH_ROLESLIST_FOR_MODULE_FAILURE: 'Organization/FETCH_ROLESLIST_FOR_MODULE_FAILURE',

    SET_ROLE_USER: 'Organization/SET_ROLE_USER',

    FETCH_ASSIGNED_MODULES_FOR_CHK: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK',
    FETCH_ASSIGNED_MODULES_FOR_CHK_REQUEST: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK_REQUEST',
    FETCH_ASSIGNED_MODULES_FOR_CHK_SUCCESS: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK_SUCCESS',
    FETCH_ASSIGNED_MODULES_FOR_CHK_FAILURE: 'Organization/FETCH_ASSIGNED_MODULES_FOR_CHK_FAILURE',

    SAVE_ASSIGNED_MODULES: 'Organization/SAVE_ASSIGNED_MODULES',
    SAVE_ASSIGNED_MODULES_REQUEST: 'Organization/SAVE_ASSIGNED_MODULES_REQUEST',
    SAVE_ASSIGNED_MODULES_SUCCESS: 'Organization/SAVE_ASSIGNED_MODULES_SUCCESS',
    SAVE_ASSIGNED_MODULES_FAILURE: 'Organization/SAVE_ASSIGNED_MODULES_FAILURE',


    LOAD_API_PROVIDERS: 'Organization/LOAD_API_PROVIDERS',
    LOAD_API_PROVIDERS_REQUEST: 'Organization/LOAD_API_PROVIDERS_REQUEST',
    LOAD_API_PROVIDERS_SUCCESS: 'Organization/LOAD_API_PROVIDERS_SUCCESS',
    LOAD_API_PROVIDERS_FAILED: 'Organization/LOAD_API_PROVIDERS_FAILED',

    GET_NOTIFICATION_API_PROVIDER: 'Organization/GET_NOTIFICATION_API_PROVIDER',
    GET_NOTIFICATION_API_PROVIDER_REQUEST: 'Organization/GET_NOTIFICATION_API_PROVIDER_REQUEST',
    GET_NOTIFICATION_API_PROVIDER_SUCCESS: 'Organization/GET_NOTIFICATION_API_PROVIDER_SUCCESS',
    GET_NOTIFICATION_API_PROVIDER_FAILURE: 'Organization/GET_NOTIFICATION_API_PROVIDER_FAILURE',

    UPDATE_API_PROVIDER: 'Organization/UPDATE_API_PROVIDER',
    UPDATE_API_PROVIDER_REQUEST: 'Organization/UPDATE_API_PROVIDER_REQUEST',
    UPDATE_API_PROVIDER_SUCCESS: 'Organization/UPDATE_API_PROVIDER_SUCCESS',
    UPDATE_API_PROVIDER_FAILURE: 'Organization/UPDATE_API_PROVIDER_FAILURE',

    POST_API_PROVIDER: 'Organization/POST_API_PROVIDER',
    POST_API_PROVIDER_REQUEST: 'Organization/POST_API_PROVIDER_REQUEST',
    POST_API_PROVIDER_SUCCESS: 'Organization/POST_API_PROVIDER_SUCCESS',
    POST_API_PROVIDER_FAILURE: 'Organization/POST_API_PROVIDER_FAILURE',
    CLEAR_ORGANIZATION_DETAILS: 'Organization/CLEAR_ORGANIZATION_DETAILS'

};

export const listOrganization = (data) => action(types.LIST_ORGANISATION, { data });
export const deleteOrganization = (data, page, size, count) => action(types.DELETE_ORGANISATION, { data, page, size, count });
export const saveOrganization = (data) => data.organizationId ? action(types.UPDATE_ORGANIZATION, { data }) : action(types.SAVE_ORGANIZATION, { data });
export const fetchOrganizationDetails = (data) => action(types.FETCH_ORGANIZATION_DETAILS, { data });

export const loadParentOrganizations = () => action(types.LOAD_PARENT_ORGANIZATIONS);
export const loadOrganizationTypes = () => action(types.LOAD_ORGANIZATION_TYPES);

export const loadStates = data => action(types.ORGANIZATION_COMMON_STATE, { data });

export const loadDistricts = data => action(types.LOAD_DISTRICTS, { data });

export const loadBlockPanchayath = data => action(types.ORGANIZATION_COMMON_BLOCK_PANCHAYATH, { data });

export const loadDistrictPanchayath = data => action(types.ORGANIZATION_COMMON_DISTRICT_PANCHAYATH, { data });

export const loadLSGI = data => action(types.LOAD_LSGIS, { data });

export const loadLSGITypes = () => action(types.LOAD_LSGI_TYPES);


export const setTabIndex = (data) => action(types.SET_TAB_INDEX, { data });

export const fetchOrganizationAssignUsers = (data) => action(types.FETCH_ORGANIZATION_ASSIGN_USERS, { data });
export const updateUserOrganizationMapping = (data) => action(types.UPDATE_CHK_USER_ORGANIZATION, { data });


export const loadOrganizationRoleTypes = (data) => action(types.LOAD_ORGANIZATION_ROLE_TYPES, { data });
export const setOrgRoleType = (data) => action(types.SET_ORGANIZATION_ROLE_TYPES, { data });
export const fetchAssignRoleInOrg = (data) => action(types.FETCH_ASSIGN_ROLE_IN_ORG, { data });
export const submitAssignRole = (data) => action(types.SUBMIT_FETCH_ASSIGN_ROLE_IN_ORG, { data });

export const fetchModulesforChk = (data) => action(types.FETCH_MODULES_FOR_CHK, { data });
export const saveModulesinOrgChk = (data) => action(types.SAVE_MODULES_FOR_CHK, { data });
export const clearCheckListInReducer = () => action(types.CLEAR_ASSIGNED_CHECKED_LIST);
export const fetchRolesforListBox = (data) => action(types.FETCH_ROLESLIST_FOR_MODULE, { data });
export const setRoleAndUser = (data) => action(types.SET_ROLE_USER, { data });

export const fetchAssignedModulesforChk = (data) => action(types.FETCH_ASSIGNED_MODULES_FOR_CHK, { data });
export const saveAssignedModulesinOrgChk = (data) => action(types.SAVE_ASSIGNED_MODULES, { data });

export const loadAPIProviders = () => action(types.LOAD_API_PROVIDERS);
export const getNotificationApiProvider = (id, notificationApiType) => action(types.GET_NOTIFICATION_API_PROVIDER, { id, notificationApiType });
export const sentApiProviderKey = (id, data) => action(types.UPDATE_API_PROVIDER, { id, data });
export const sentApiProviderKeyForPost = (id, data) => action(types.POST_API_PROVIDER, { id, data });

export const clearOrgDetails = () => action(types.CLEAR_ORGANIZATION_DETAILS, {});

